### ISSUE TITLE
Member import 'spins' forever

### ISSUE THREAD

**Issue by goetzk** [tendenci/tendenci#470] opened 2015-12-04 08:42 UTC
I've tried doing an import through http://example.com/profiles/import/ and i can leave the window open all night and not come back to imported users ready for stage 2.
I tried http://example.com/memberships/import_default/preview/1/ after seeing #412 and that has taken me to stage 2 in under a minute.

**Comment by jennyq** [comment] 2015-12-19 23:22
@goetzk We'll take a look at it. How many users were you trying to import?

**Comment by goetzk** [comment] 2015-12-20 04:42
Um, let me check.

    wc -l people-export-converted.csv 
    4048 people-export-converted.csv

A decent number (though I'm guessing well within the expected limits).

**Comment by jennyq** [comment] 2016-06-29 21:44
@goetzk, I cannot replicate the issue. Do you use virtualenv for the site? If so, please check if you have upstart script set up properly. Specifically, check if the line `. /<path-to-virtualenv>/bin/activate` is in there. http://tendenci.readthedocs.io/en/latest/installation/installation.html#setting-up-upstart

**Comment by eschipul** [comment] 2016-06-30 21:27
My thoughts on this - fundamentally user imports and exports should be background tasks added to a queue. Notification on completion should be duplicated with a jquery alert as well as an email. We do this with newsletters so that might be a place to look for design patterns. 

Security concern from experience - in the past we have built these exports as text files out of the root of the site. It is critical that they be time bound - meaning that if someone does an export and it is saved to /media/exports/LTw3qT3CiVnsMx-2016-30-16-18-32-username.csv or similar, that there is a cron job that deletes these four hours after they are created for example. Leaving the data on the server just creates a target worth attacking.

@goetzk - it would be helpful if you had a trace or log showing the error. I'm not sure how I would do this myself, which is a problem in and of itself, but with more data we can zero in on it. No doubt it is happening, so it is just a matter of finding the cause.

My debug method - I break the list up into smaller chunks. It is almost assuredly an individual piece of bad data, or windows line returns, or a null value in a pk field. That type of thing. The import file should be conditioned by tendenci to handle all of these possibilities and prevent them from causing an error. Like I know sometimes if I save a csv from excel, open it in sublime or vi, then save it again, frequently the problem goes away. But that is a complete hack and shouldn't be needed.

It is definitely something Tendenci should handle. Finding it? As I said, I break it up. If you import 100 records at a time given our current debug limitation, that would let you find the block of 100 that causes the error. Then do 10 at a time. Then look at the data for weird character types.... check if the database is UTF-8 and not "Latin", etc... And as you said - this might be better combined with #470

**Comment by eschipul** [comment] 2017-06-30 05:25
Closing old tickets. Resubmit if still an issue.

**Closed by eschipul** 2017-06-30 05:25 UTC
