### ISSUE TITLE
Export hangs

### ISSUE THREAD

**Issue by rjdini** [tendenci/tendenci#862] opened 2020-06-03 14:08 UTC
using 12.07
Trying to export users, or members, while operating as superuser.
The export page calls for confirmation of password.
Then select 'export main fields', and activate export.
Page says (according to export case) 'check the status of export later' or 'will email on completion'
and moves to something like: /profiles/export/status/1591192456/
Here the process hangs.
(other email functions are working normally)

Any suggestions please?

**Comment by goetzk** [comment] 2020-06-05 10:53
@rjdini I've also confirmed a problem on 12.0.7.

```
==> /srv/tendenci/logs/tendenci-test.error.log <==
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/tendenci_test/environment/src/tendenci/tendenci/apps/memberships/management/commands/membership_export_process.py", line 87, in handle
    ids=ids)
  File "/srv/tendenci_test/environment/src/tendenci/tendenci/apps/memberships/utils.py", line 486, in process_export
    for row_dict in membership_rows:
  File "/srv/tendenci_test/environment/src/tendenci/tendenci/apps/memberships/utils.py", line 280, in get_membership_rows
    field_name, profile, field_name in foreign_keys)
  File "/srv/tendenci_test/environment/src/tendenci/tendenci/apps/memberships/utils.py", line 311, in get_obj_field_value
    value = value.id
AttributeError: 'str' object has no attribute 'id'
```

The problem function is this:
```
def get_obj_field_value(field_name, obj, is_foreign_key=False):
    value = getattr(obj, field_name)
    if value and is_foreign_key:
        value = value.id
    return value
```
This is one of those strange issues where that function hasn't changed since 2014 and the directly calling code hasn't been touched since 2015.

Its possible its a disconnected change which has resulted in this - perhaps a model change which changed the foreign key.
@jennyq is going to have the best overview of what changed recently which might have been involved.

**Comment by rjdini** [comment] 2020-06-05 12:08
Thanks @goetzk 

I should add that the related import functions are also not working.

**Comment by jennyq** [comment] 2020-06-05 23:20
Thanks @goetzk for the additional info. Looked at it today but I cannot replicate the issue. Going to look into more later.

**Comment by rob-hills** [comment] 2020-06-06 09:37
@jennyq could this error be related to the data in our system?  The Traceback @goetzk posted above is from our system and we migrated our original member dataset from our previous CiviCRM database. We used the Tendenci import process, however we had to massage our data a bit to get it to import without errors.

I thought I'd mention this in case there might be something in the data itself causing this problem.  If you think that could be the case and can give me some clues about where to look, I am happy to dig through the database.

**Comment by rjdini** [comment] 2020-06-06 11:18
@jennyq @rob-hills  I add the following in case it is helps toward the solution. 
I discovered the export problem in the context of wanting to import a new group of users. As a test case I used an import CSV file that had been used successfully to import users in tendenci 11.
In 12.07 the import hung.  So I tried exporting the upload Template available on the Upload page. This download is successful. I loaded that Template with  names and email of two fake users (but with valid email addresses), and tried to import this test file. The import does not complete. So then I tried exporting the users as CSV, hoping to check again the template in that way. This export of users does not complete.

**Comment by rjdini** [comment] 2020-06-10 23:16
Thank you. 
I have rebuilt 12.0.8. But unfortunately,  the issues persist as above.  
I noticed that the pip install complains that there is a conflict between botocore 1.15.49 and docutils. I
I uninstalled botocore, and replaced docutils with version 0.16.  This didnt help the problems above.
Any suggestions for where I might look in order to diagnose this issue??

**Comment by rob-hills** [comment] 2020-06-11 03:11
Hi @jennyq,

> @rob-hills, it could be related to your data, but I'm not sure. @rjdini, I followed the process you did, but still couldn't reproduce.
> 
> Anyway, I've pushed out a commit [608fcfb](https://github.com/tendenci/tendenci/commit/608fcfbb24e8344858c0baaf7d7f39dfe3b8379d). Can you please check if that fixes the issue?

Many thanks for this.  I will pull this in to our test site later today Australian time and we can test it and feed back our results.

**Comment by CWalkden** [comment] 2020-06-11 06:02
> Hi @jennyq,
> 
> > @rob-hills, it could be related to your data, but I'm not sure. @rjdini, I followed the process you did, but still couldn't reproduce.
> > Anyway, I've pushed out a commit [608fcfb](https://github.com/tendenci/tendenci/commit/608fcfbb24e8344858c0baaf7d7f39dfe3b8379d). Can you please check if that fixes the issue?
> 
> Many thanks for this. I will pull this in to our test site later today Australian time and we can test it and feed back our results.

I've tested this today as installed by @rob-hills, and the issue persists.
I'm not certain that our issue is the same as the one reported by @rjdini.  On our system, choosing 'Export main fields' works correctly.  We only get the issue when we select 'Export all fields'.

**Comment by rjdini** [comment] 2020-06-11 08:02
@jennyq @CWalkden 
In my case the problem exists for both main_fields and all_fields.
However - some good news....   
./manage.py profile_export_process completes in a few seconds, and writes a correct .csv file to media/export/profiles.  
The export is performed by process_export in profiles/utils.py.   However the email notification at the end of that call is not being triggered. The code there  is
   # notify user that export is ready to download
    [user] = User.objects.filter(pk=user_id)[:1] or [None]
    if user and user.email:

The execution of the export is  managed from profiles/views.py  profile_export

# start the process
        subprocess.Popen([python_executable(), "manage.py",
                          "profile_export_process",
                          '--export_fields=%s' % export_fields,
                          '--identifier=%s' % identifier,
                          '--user=%s' % request.user.id])
I do not understand how the request.user.id is transferred to this call (beyond my pay-grade...!). But I guess that if it failed, then utils would not be able to send the email??

Also in views.py profile_export_status checks to see if the output csv file is present.  

 export_path = 'export/profiles/%s.csv' % identifier
     download_ready = False
     if default_storage.exists(export_path):
         download_ready = True

It seems that this code is in fact returning False, despite the existence of the output file. So once again I guess the %s is not being properly transferred.

**Comment by rjdini** [comment] 2020-06-11 08:39
On the related Import issue:
The relevant .csv is correctly uploaded to media/import/profiles.
But then the process hangs.

**Comment by rob-hills** [comment] 2020-06-11 09:44
In our case, this is the traceback from @CWalkden 's attempt to export members:
```
TIME="2020-06-11 15:57:34,861" LEVEL=DEBUG PID=15989 LOGGER="django.template" FILE="/srv/tendenci_test/environment/lib/python3.6/site-packages/django/template/base.py" LINE=872 FUNC="_resolve_lookup" MSG="Exception while resolving variable 'MODULE_PAGES_LABEL_PLURAL' in template 'memberships/default_export.html'."
Traceback (most recent call last):
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/srv/tendenci_test/environment/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'MODULE_PAGES_LABEL_PLURAL'
```
It's a bit tricky because our debug log is _**full**_ of KeyError exceptions!

**Comment by CWalkden** [comment] 2020-06-17 10:29
We've installed 12.0.9, and the exports are now working for us.  Thanks!

**Comment by jennyq** [comment] 2020-06-17 13:38
Great! 

@rob-hills, the reason you saw `KeyError: 'MODULE_PAGES_LABEL_PLURAL'` in debug.log is because that template variable does not exist. The template system replaces a non-existing variable with an empty string. So, it's harmless but it does log an error in the debug.log. It's been fixed in the commit https://github.com/tendenci/tendenci/commit/d433ab354bf83001b7ca4f155ce1c1aba103c8bc.

**Closed** 2020-06-17 13:38 UTC

**Comment by rjdini** [comment] 2020-06-17 14:53
Well, unfortunately, I have installed 12.0.9 and continue to have the same problems for both import and export.

I should point out that we are running this tendenci in docker. This could introduce a problem, but it seems unlikely because we have been running 11 on docker for 2 years without difficulty.

**Comment by jennyq** [comment] 2020-06-17 15:24
Have you restarted your container after update?

**Comment by rjdini** [comment] 2020-06-17 20:41
Yes @jennyq  
I have a standard script that pulls tendenci-master.zip and then builds essentially according to the tendenci basic installation instructions.  I  have used the same script for the past year at least. fter the image is built, I launch using docker-compose into a standard enviroment that has been in use for the past 2 years. The only change is to the docker tendenci image version, now at 12.0.9.  The version is confirmed by the Support > drop-down.
All other functions are operating normally (eg docs and images can be up- and down-loaded)

As in my comments earlier in this issue,  on the 11th June the required .csv files were indeed exported to the media directory, but it appeared that although the output process had put them there, views.py did not detect their presence, and so the output process does not complete,  

Now (12.0.9)  only empty <identifier>_temp.csv files are being written.  
 
The file permissions are set for www-data, as in the installation instructions, and the tendenci process in the container is initiated by gunicorn, and running as www-data.
Baffling....

**Comment by rjdini** [comment] 2020-06-17 23:08
T12.0.09
running ./manage.py profile_export_process, without arguments, successfully exports all fields of all profiles to media/export/<identifier>.csv   (running as root, or as www-data)

**Comment by rjdini** [comment] 2020-06-18 19:35
Yes, thanks @jennyq , I have done that.

I think I have isolated the problem. When the calls are made to manage.py (in profiles/utils.py, and views.py) then python complains that it cannot find manage.py.

I think this is it.

For the past years I have been running Tendenci in a venv inside docker. I realize that it is not good practice to run venv inside docker. However, I wanted to keep the installation aligned with yours. It is in that situation that I discovered the 'cannot find manage' error.  Now I am busy trying a direct installation (no venv).  Lets see...

**Comment by rjdini** [comment] 2020-06-18 19:43
Ok  @jennyq  the problem is resolved. 
I built a new version of the docker container that avoids venv. But that did not solve the issue.

The solution turned out to be setting PYTHONPATH to point to the Tendenci root.
Why this should be the case now, and not previously, i do not know!
However it seems that PYTHONPATH is necessary for docker, T12, Django 2, and Python3.7

**Comment by goetzk** [comment] 2020-06-18 20:41
Excellent detective work!
Karl

On 19 June 2020 05:43:17 GMT+10:00, Rodney Douglas <notifications@github.com> wrote:
>Ok  @jennyq  the problem is resolved. 
>I built a new version of the docker container that avoids venv. But
>that did not solve the issue.
>
>The solution turned out to be setting PYTHONPATH to point to the
>Tendenci root.
>Why this should be the case now, and not previously, i do not know!
>However it seems that PYTHONPATH is necessary for docker, T12, Django
>2, and Python3.7
>
> 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tendenci/tendenci/issues/862#issuecomment-646268869

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rjdini** [comment] 2020-06-18 20:53
Thank you @goetzk !

**Comment by jennyq** [comment] 2020-06-21 21:54
@rjdini Awesome! If Tendenci is installed in the global default location like _site-packages_, it shouldn't need to be added to the PYTHONPATH. Maybe your container works differently?
