### ISSUE TITLE
Member expiration and renewal

### ISSUE THREAD

**Issue by dco5** [tendenci/tendenci#415] opened 2015-09-20 23:09 UTC
When an expired member renews it's membership it changes the status of the member from expired to Archive. Also it creates another entry in the membership list as you can see on the attached image.

![screenshot](https://cloud.githubusercontent.com/assets/3612771/9983474/a1bb4040-5fc2-11e5-8d31-3bc5b349136d.png)

**Comment by eschipul** [comment] 2015-09-21 01:28
@dco5 Jaime - this is by design. On release 1 through 4.3, membership was an attribute of a user. Which at first seems fine, but over time, like with people who have been using Tendenci since 2001, this creates a reporting gap.

To clarify, what I mean by that is that if a person is bob.ismember=1 and then leaves the organization and it becomes bob.ismember=0, then rejoins and is once again bob.ismember=1, well, you have no way of knowing WHY they left, what the history of an individual is and why they would be a member of your organization or not.

Caveat - so we did restructure the data but some obvious missing reports are:
Membership renewal percentage over time
Membership attrition rate (can you recruit them back?)
Membership location over time (think leaflet.js which is why I insist on the postgres GIS extensions)

So while those reports don't exist yet, the fact that a new membership record is created is definitely by design as it facilitates providing information to help an organization. You can have a leaflet.js map of the demographics of your membership over time by location for example. Does that report exist right now? Nope. But we CAN in the future get that data if we record it.

So, a membership should be for the term of the membership. Typically one (1) year. When they renew a new membership application snapshot, possibly with their new address, is generated. Only a super-user will see this data but you do have data to help you serve your membership better.

Check  if /explorer/ is enabled on your install and you can do some ad hoc queries, or just go straight to your postgres db and run some queries. Does that make sense?

And yes, perhaps I plan too big but eventually block walking and demographic analysis to help in a humanitarian crisis is part of the overall plan. Hence the "social-services" add-on which in the refactored 7.1 will be part of core. Because emergency response is definitely core and definitely requires GiS and mapping.

I hope this helps and we are DEFINITELY open to new ideas on how it could be done better?

**Comment by eschipul** [comment] 2015-09-21 01:31
If this answers your question please do mark this closed. If not, hit me up. We don't have the new forums working yet but will soon. We're also setting up a proper listserv so we can all communicate creative ideas better than just with issues on github. THANK YOU!

**Comment by dco5** [comment] 2015-09-21 01:47
I can understand the idea, but then why is the new membership also __Archive__? One should be Archive so that we can have a good history of the membership over time, but the new one should be Active since the member just renewed his membership. When I go to the user profile it says it is not a member. That is what is throwing me off. But now I do understand the need for creating a new membership with every renewal.

**Comment by eschipul** [comment] 2015-09-21 02:57
Then that's a bug. Let me test. Def should not show as nonmember on
renewal. Hmmmm

**Comment by jennyq** [comment] 2016-05-20 22:09
@dco5 I cannot replicate the issue. Can you please test again to see if the issue is still there?

**Comment by jennyq** [comment] 2016-06-15 18:37
Closing it... Feel free to reopen it if the issue persists.

**Closed by jennyq** 2016-06-15 18:37 UTC
Labels: Bug
