### ISSUE TITLE
Demo Instance Bug: site menu shows after login

### ISSUE THREAD

**Issue by supersexy** [tendenci/tendenci#792] opened 2019-07-06 11:28 UTC
After a login to the demo instance there is still the site menu visible, what leads to confusion - I assume this is a bug. 

If this is not a bug - please do not do that, that is a really bad idea. Administrative areas and user facing frontend should be completely separated UI areas, do not mix that up.

**Comment by eschipul** [comment] 2019-07-06 17:39
It is not a bug. Nor an issue.

The top nav bar is specific to a logged in user’s permissions. 

AMS software is not something where you can separate admin / management / user functionality for a logged in user without making it cumbersome.

I respect your feedback. I also completely disagree as I suspect you are new to the AMS space or perhaps aren’t familiar with the delegation common in associations to ease the burden on the Executive Director or the BOD.

I fundamentally do not agree with blanket statements like “admin areas and user facing frontends should be completely separate UIs.” 

With humility and respect, I ask you, have you ever managed an association with over 100,000 users? In my experience it requires a team effort and delegation. And a common UI that is context specific.

Closing this issue. But as always, I remain open to further thoughtful conversation. And I appreciate your thoughts and contributions.

 - Ed

**Closed by eschipul** 2019-07-06 17:39 UTC

**Comment by supersexy** [comment] 2019-07-08 20:24
Wow, that is really strange. Very awkward. Hopefully somebody can convince you to hire a design team one day. Good Luck!
